### ISSUE TITLE
publish the transpiled package so we can consume the library from other apps 

### ISSUE THREAD

**Issue by elmariachi111** [orYoffe/jstates-react#1]
using CRA (or Gatsby)

```js
//components/api.js
import { State } from "jstates-react";

const initialState = {
    accessToken: null,
    refreshToken: null,
    expires: 0
};

const authState = new State("auth", initialState);
export default authState
```

```js
//App.js
import { subscribe } from "jstates-react"
import authState from './components/api'

const App = ({ auth, setAuth }) => {
...
}

const mapStates = ({ authState }) => ({
  auth: () => authState.state,
  setAuth: newToken => authState.setState(state => ({ accessToken: newToken })),
});

export default subscribe(App, [authState], mapStates)
```

calling `yarn run start` yields
```
SyntaxError: /..../node_modules/jstates-react/index.js: Unexpected token (69:13)

  67 | 
  68 |     render() {
> 69 |       return <Compt {...this.props} {...this.state} />;
     |              ^
  70 |     }
  71 |   };
  72 | }
```

Since Webpack isn't considering node_modules for JSX transformations I tried switching that on in Gatsby (https://www.gatsbyjs.org/docs/add-custom-webpack-config/#modifying-the-babel-loader) but ran into absolutely different issues then. Think your library package should expose the transpiled target :) This might give some inspiration: https://github.com/grommet/grommet/blob/master/package.json or https://jasonwatmore.com/post/2018/04/14/react-npm-how-to-publish-a-react-component-to-npm

**Comment by orYoffe** [comment]
hey @elmariachi111 thanks for the info. just published v0.2.6 hope it solves the issue. 
Please reopen the issue if it doesn't fix the problem you had :)
https://unpkg.com/jstates-react/dist/index.js
